# Copyright (C) 2021 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker compose up
#           docker compose down
#
#           https://localhost:8080 mit admin und p
#
# evtl.:    docker compose exec keycloak bash
#           nl statt cat

---
# https://docs.docker.com/compose/compose-file
# https://docs.docker.com/compose/compose-file/compose-file-v3
services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    #depends_on: [postgres]
    ports:
      - published: 8080
        target: 8080
    volumes:
      - type: bind
        source: C:/Zimmermann/volumes/keycloak
        # mit Unterverzeichnis h2
        target: /opt/keycloak/data
      # ggf. /opt/keycloak/conf/keycloak.conf
    environment:
      TZ: Europe/Berlin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: p

      #KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak?ssl=allow
      #KC_DB_SCHEMA: public
      #KC_DB_USERNAME: keycloak
      #KC_DB_PASSWORD: keycloak
      #KC_HOSTNAME: idp-dev.gruchalski.com
      #KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      #KC_HTTP_RELATIVE_PATH: /
    container_name: keycloak
    hostname: keycloak
    user: keycloak:1000
    # --features=token-exchange
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
